name: CD with Docker

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh and docker
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/jimlyassidqi/projects/belajar-cicd-docker
            git pull origin main
            docker build -t belajar-cicd-docker .
            docker stop belajar-cicd-docker-container || true
            docker rm belajar-cicd-docker-container || true
            docker run -d --name belajar-cicd-docker-container -p 30001:3001 belajar-cicd-docker
